name: Ruby

on:
  schedule:
    - cron: "0 0 0 1"
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  readme:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5

    - uses: actions/cache@v2
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Generate readme
      env:
       TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
       TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
       TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
       TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       HCTI_API_USER_ID: ${{ secrets.HCTI_API_USER_ID }}
       HCTI_API_KEY: ${{ secrets.HCTI_API_KEY }}
      run: bundle exec ruby generate.rb

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Joe Ingeno
        author_email: joe.ingeno@protonmail.com
        message: "Auto updating my README."
        add: "*.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
